linkedin/transport

transportable-udfs-test/transportable-udfs-test-spark/build.gradle
`jackson-module-scala` and `jackson-module-paranamer` need to have the same minor version due to API incompatibilities between jackson minor versions. Spark (Core/SQL) brings in `jackson-module-scala:2.6.7.1` which brings in `jackson-module-paranamer:2.7.9` thus introducing incompatibility. Previously we pulled down `jackson-module-paranamer` to 2.6.7 to fix this issue. However if there is another dependency which requires `2.7.9` of `jackson-module-paranamer`, it will be pulled up again due to gradle dependency resolution leading to the below issue. It is better to pull up the version of `jackson-module-scala` instead.
```
Caused by:
com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.7.9
at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModul …
```
=> Update jackson-module-scala dependency version

transportable-udfs-codegen/src/main/resources/wrapper-templates/spark, transportable-udfs-codegen/src/test/resources/outputs/sample-udf-metadata/spark/sources/udfs/spark/OverloadedUDF.scala, transportable-udfs-codegen/src/test/resources/outputs/sample-udf-metadata/spark/sources/udfs/spark/SimpleUDF.scala, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/Defaults.java, transportable-udfs-spark/build.gradle
- Do not explicitly specify Scala version, rely on Scala version coming from Spark
- Do not shade Transport's Scala classes. Relocation does not work well for Scala classes. This is because Scala injects a `@ScalaSignature` annotation with pickled signature of the class and currently no shading library handles relocation of classes names inside the signature. This causes usage of the UDFs to break when used inside the Scala REPL, because REPL depends on the signature. (Might also break inside non-REPL usages if the user relies on Scala Reflection; Java Reflection usage works)
- Provide a UDF registration helper which is decoupled from Transport's shading policy for its internal Scala classes. Example usage 
```
scala> import com.linkedin.transport.examples.spark.NumericAddFunction
scala> …
```
=> Fix shading issues in generated Spark artifacts

transportable-udfs-plugin/build.gradle, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/Defaults.java
- The idea plugin needs a scala-library on the classpath when the scala plugin is applied even when there are no scala sources. So we explicitly add the scala library as a dependency of main sourceSet.
- `presto-main:tests` is a transitive dependency of `transportable-udfs-test-presto`, but some POM to IVY converters drop dependency classifiers, so we apply this dependency explicitly.
=> Fix issues with Idea plugin and presto tests

transportable-udfs-hive/src/main/java/com/linkedin/transport/hive/StdUdfWrapper.java, transportable-udfs-presto/src/main/java/com/linkedin/transport/presto/FileSystemClient.java, transportable-udfs-spark/src/main/scala/com/linkedin/transport/spark/StdUdfWrapper.scala, transportable-udfs-test/transportable-udfs-test-generic/src/main/java/com/linkedin/transport/test/generic/GenericStdUDFWrapper.java, transportable-udfs-utils/src/main/java/com/linkedin/transport/utils/FileSystemUtils.java, transportable-udfs-utils/src/test/java/com/linkedin/transport/utils/FileSystemUtilsTest.java
Problem statement: I want fully qualified URIs to work in required files function of a UDF. Currently, to resolve #LATEST, the code assumes that the filesystem in use is coming from the configuration option fs.defaultFS. This change does by switching usages of FileSystem.get(conf) to FileSystem.get(URI, conf). This change is similar to the internal RB (rb no. 1901530) I posted recently. 
Following steps were used for testing:
1. setting defaultFS to an abfs directory 
2. setting the protocol to be file:/// in unit tests. 
3. running the FileSystemUtilTest
=> Allow for absolute paths instead of assuming defaultFS in UDF's required files

transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/TransportPlugin.java
Fixes #36
Manually applied jacoco plugin to `transportable-udfs-example-udfs`
Before the change:
Presto Test for `transportable-udfs-example-udfs` fails with
```
Caused by: java.lang.IllegalArgumentException: Cannot determine size of boolean[] because it contains an array
at io.prestosql.spi.block.BlockBuilderStatus.deepInstanceSize(BlockBuilderStatus.java:63)
at io.prestosql.spi.block.BlockBuilderStatus.deepInstanceSize(BlockBuilderStatus.java:78)
at io.prestosql.spi.block.BlockBuilderStatus.deepInstanceSize(BlockBuilderStatus.java:78)
at io.prestosql.spi.block.BlockBuilderStatus.<clinit>(BlockBuilderStatus.java:26)
... 81 more
```
After change:
All tests pass
After verified with the following print statements in `build.gradle` of `transportable-udfs-example-udfs`
``` …
```
=> Disable Jacoco for platform tests

transportable-udfs-utils/src/main/java/com/linkedin/transport/utils/FileSystemUtils.java
Why: we don't need it and it's breaking presto (see internal jira: PRESTO-2221)
What changed: instead of checking configuration for hints on whether we
are unit testing, we trust the URI's protocol
Tests performed: ./gradlew build
=> FileSystemUtils: remove an unreliable check for unit testing

transportable-udfs-presto/src/main/java/com/linkedin/transport/presto/FileSystemClient.java, transportable-udfs-utils/src/main/java/com/linkedin/transport/utils/FileSystemUtils.java
In a3906a4bf335757d6da786db3582327379d4960a, we inadvertently changed the behaviour of FileSystemClient.java(https://github.com/linkedin/transport/commit/a3906a4bf335757d6da786db3582327379d4960a#diff-0e951023ba157de4b5b807e63e25e579L56-R56) to not pass a custom FileSystem object to FileSystemUtils. The expectation was that `new Configuration()` would provide all the necessary information to interact with DistributedFileSystem. However, for Presto, `new Configuration()` is not enough as it does not contain the necessary HDFS configs. Instead for Presto we have to explicitly load `etc/hdfs-site.xml` and `etc/core-site.xml` which are configured on our clusters.
This change reverts the behavior for Presto by passing a custom Configuration object which contains the HDFS configs.
=> Presto: Pass custom configuration object when using FileSystemUtils

transportable-udfs-presto/src/main/java/com/linkedin/transport/presto/StdUdfWrapper.java
- Presto uses independent caches for ScalarFunction and ScalarFunctionImplementation. So there are possibilities of multiple instances of ScalarFunctionImplementation existing for the same UDF.
- In such a case it may be possible for multiple parallel executions of the UDF using two different instances of ScalarFunctionImplementation to corrupt the shared state in ScalarFunction (in our case StdUdfWrapper)
- So it is best if we do not share any mutable state between the ScalarFunctionImplementation instances. Currently _requiredFilesNextRefreshTime was being shared between instances.
Testing Done:
- Unfortunately, we are not able to reproduce the issue locally or even on the cluster deterministically. So it is hard to write a specific unit test.
- Current unit tests pass
- Ran a local …
=> Presto: Make ScalarFunctionImplementation state independent of StdUdfWrapper

defaultEnvironment.gradle, docs/transport-udfs-presto.patch, transportable-udfs-examples/build.gradle, transportable-udfs-plugin/build.gradle, transportable-udfs-presto/src/main/java/com/linkedin/transport/presto/PrestoFactory.java, transportable-udfs-presto/src/main/java/com/linkedin/transport/presto/StdUdfWrapper.java, transportable-udfs-presto/src/main/java/com/linkedin/transport/presto/data/PrestoMap.java
Some major changes:
- `SqlFunction`, `SqlScalarFunction` and `ScalarFunctionImplementation` have evolved
in https://github.com/prestosql/presto/pull/1764
- `Metadata::getScalarFunctionImplementation` evolved in https://github.com/prestosql/presto/pull/1039
- Type signature parser was moved to presto-main in https://github.com/prestosql/presto/pull/1738
Tests done:
- `./gradlew build` passes inside `transportable-udfs-examples` 
- Tested end-to-end with Presto 333 using one of the example UDFs `array_fill`. It works well
=> Upgrade to PrestoSQL 333

transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/TransportPlugin.java, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/TransportPluginConfig.java
This PR introduces the ability to configure aspects of the Transport Plugin. Specifically there are 3 parameters that may be configured: 
1. the name of the "main" source set to scan for UDFs and extend (Default to "main") 
2. the name of the "test" source set to extend for platform-specific test source sets (Default to "test")
3. the output directory to place generated wrappers, w.r.t the project root (Default to project build directory) 
Since these parameters are all used immediately when the plugin is applied, using gradle extension does not appear to be a viable option to set them. Instead, these parameters are configurable using gradle project properties. Nonetheless, I've chosen to expose the config to the plugin as an extension so that configs using the extension convention can be …
=> Transport Plugin Config

build.gradle, transportable-udfs-test/transportable-udfs-test-spark/build.gradle
Transport as a library should only expose `slf4j-api` to its consumers and should not expose any SLF4J bindings.
http://www.slf4j.org/faq.html#maven2
> Thus, as far as your users are concerned you are exporting slf4j-api as a transitive dependency of your library, but not any SLF4J-binding or any underlying logging system.
Unfortunately `hadoop-common` does expose `sl4fj-log4j12` as a transitive. This can cause `StackOverflowError` if another binding is also present on the classpath. This issue seems to popup frequently in Presto tests and on the Presto cluster. We as a library, should remove the bindings from our transitives and ensure we don't introduce any ourselves.
Note that we still keep the `slf4j-simple` binding for tests and explictly for spark test framework as Spark Core and …
=> Remove slf4j-log4j12 from Transport dependency graph

build.gradle
The two things we would be interested in with the bump
- Remove shipkit's dependence on a now deprecated Github API which will stop working in October https://github.com/mockito/shipkit/pull/871
- Update bintray plugin version which I had read reduces publish slowness https://github.com/mockito/shipkit/pull/850
Tested by running `./gradlew performRelease -PdryRun` locally
=> Bump shipkit version

transportable-udfs-examples/transportable-udfs-example-udfs/src/test/java/com/linkedin/transport/examples/TestBinaryDuplicateFunction.java, transportable-udfs-test/transportable-udfs-test-presto/src/main/java/com/linkedin/transport/test/presto/PrestoSqlFunctionCallGenerator.java, transportable-udfs-test/transportable-udfs-test-spi/src/main/java/com/linkedin/transport/test/spi/SqlFunctionCallGenerator.java
Fixes #52 
The existing method for test binary data types (converting them to strings) does not work for unsigned byte values > 127. `new String()` will replace these bytes with Unicode replacement character https://www.fileformat.info/info/unicode/char/0fffd/index.htm
We should encode the byte values as base64 for generating the SQL string and convert them to back to binary before passing to the UDF
=> Fix test SQL generation for binary inputs

transportable-udfs-spark/src/main/scala/com/linkedin/transport/spark/data/SparkMap.scala
Currently, accessing the keySet via: _mapData.keyArray().array.iterator or values via: _mapData.valueArray().array.iterator fails as its underlying type in Spark is UnsafeArrayData.
UnsafeArrayData does not allow accessing the raw array: https://github.com/apache/spark/blob/master/sql/catalyst/src/main/java/org/apache/spark/sql/catalyst/expressions/UnsafeArrayData.java#L108 .
Creating the mutable map solves this problem.
=> Create a MutableMap when accessing keySet and values in SparkMap

transportable-udfs-avro/src/main/java/com/linkedin/transport/avro/AvroWrapper.java, transportable-udfs-avro/src/test/java/com/linkedin/transport/avro/TestAvroWrapper.java, transportable-udfs-avro/src/test/java/com/linkedin/transport/avro/typesystem/TestAvroBoundVariables.java
This PR just adds more support on Avro type with simple Avro Union so that it can be used independently outside of Transport UDF API.
The change is backward compatible and should not affect the normal execution path of Transport UDF on Avro type.
=> Support simple Avro Union schema

transportable-udfs-avro/src/main/java/com/linkedin/transport/avro/AvroWrapper.java, transportable-udfs-avro/src/test/java/com/linkedin/transport/avro/TestAvroWrapper.java
When reading Avro, objects of type String  may be passed in. Since Transport uses Utf8 types for AvroString, this can lead to incompatibility issues.
=> Support conversion of String type to Utf8 in AvroWrapper

README.md, build.gradle, gradle/checkstyle/checkstyle.xml, gradle/wrapper/gradle-wrapper.properties, transportable-udfs-examples/build.gradle, transportable-udfs-examples/gradle/wrapper/gradle-wrapper.properties
Motivation:
As part of the Trino upgrade/migration (#66), we need to isolate and build transport modules for different engines with different jdk versions. For instance, Spark & Hive needs to build with jdk8 and Trino has a build requirement on jdk11. By moving to gradle 6.7, we can leverage [toolchains](https://docs.gradle.org/current/userguide/toolchains.html) which will help in easier configuration of different aspects of the build.
=> Upgrade to gradle 6.7

transportable-udfs-avro/build.gradle
There doesn't seem to be any impact to the code. gradle build passes.
=> Bump Avro dependency to 1.10.2 (from 1.7.7).

.github/workflows/ci.yml
The previous github action flow failed in compilation because it's using jdk 11 to compile, which is wrong, we should use jdk 8 as default, only the trino modules will be using jdk11, but that is taken care of by the module specific gradle setting:
```
toolchain {
languageVersion = JavaLanguageVersion.of(11)
}
}
```
in #69 .
=> Update ci.yml java version to 8

transportable-udfs-hive/build.gradle, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/Defaults.java, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/DependencyConfiguration.java, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/SourceSetUtils.java, transportable-udfs-test/transportable-udfs-test-hive/build.gradle
org.pentaho:pentaho-aggdesigner-algorithm is official sunset by the author. The artifactory has been official removed from the maven repository. It is causing the build failure of Transport UDF.
* What went wrong:
Execution failed for task ':transportable-udfs-test:transportable-udfs-test-hive:compileJava'.
> Could not resolve all files for configuration ':transportable-udfs-test:transportable-udfs-test-hive:compileClasspath'.
> Could not find org.pentaho:pentaho-aggdesigner-algorithm:5.1.5-jhyde.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom
- https://jcenter.bintray.com/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-j …
=> Fix org.pentaho:pentaho-aggdesigner-algorithm sunset problem

.github/workflows/ci.yml
Currently the transportable-udfs-examples is not being built as part of pull requests. Adding this to CI to enable validations.
=> Update ci.yml to also build the udf-examples folder

transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/Defaults.java
A temporary solution to resolve the issue - two transport UDF cannot run in spark shell simultaneously.
The current solution may not be the best solution. The tradeoff is if multiple UDFs can be generated from multiple transport UDF versions
The client still can use the following patten to register the UDF function via Spark.
import com.linkedin.transport.example.spark.ExampleUDF
val exampleUDF = ExampleUDF.register("example_udf")
However, using the StdUDFRegistration.regsiter() Utils to register the UDF function will not be supported.
Notes:
com.linkedin.trasnport.spark.stdUDFRegistration & com.linkedin.transport.spark.SparkStdUDF CANNOT be shaded
due to the spark template is applied to generate the spark wrapper class.
=> A solution to fix running multiple UDFs in Spark issue

.github/workflows/ci.yml
Let's keep the step trigged with faked ./gradlew clean action. It can help us to verify if the CI/CD works will or not right now.
=> Temporarily pause the `performRelease` stage

transportable-udfs-spark_2.11/src/main/scala/com/linkedin/transport/spark/StdUdfWrapper.scala
Previously, there's no contract that can let us make sure the `StdUdfWrapper` 's `initialize` method will always happen-before the `eval` method, rendering `NPE`s where the fields inside `initialize` not initialized when they are directly accessed in `eval`.
This change utilizes the `lazy val` feature of scala to makes sure the happens-before contract of `initialize` and `eval`. We also adds a contract to make `initialize` happens-before`checkInputDataTypes`, as `checkInputDataTypes` is also part spark's `Expression` contract.
=> Transport-Spark: Ensure initialize is called before eval

transportable-udfs-spark_2.11/src/main/scala/com/linkedin/transport/spark/StdUdfWrapper.scala
Before this patch, the `getRequiredFiles` will access `SparkSession` when it gets called on the spark executor, which will throw an exception:
```
java.lang.IllegalStateException: SparkSession should only be created and accessed on the driver
```
This patch adds a condition check to make sure the `getRequiredFiles` is only called on the driver, see ref: https://github.com/apache/spark/blob/93f646dd00ba8b3370bb904ba91862c407c62cc2/sql/core/src/main/scala/org/apache/spark/sql/SparkSession.scala#L1154
=> Transport-spark: Only add files to sparkContext from driver

transportable-udfs-spark_2.11/src/main/scala/com/linkedin/transport/spark/StdUdfWrapper.scala
The previous attempt #115 that tried to fix the issue seems not working, as it still throws NPE as mentioned in https://github.com/linkedin/transport/pull/115#discussion_r844370883.
This patch uses another approach: by refactoring the `getRequiredFiles` so that it initialize `_distributedCacheFiles` in both driver and executor, but only add those files when on driver.
=> Refactor getRequiredFiles to not add files in executor

transportable-udfs-examples/transportable-udfs-example-udfs/build.gradle, transportable-udfs-plugin/build.gradle, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/Defaults.java, transportable-udfs-test/transportable-udfs-test-trino/build.gradle, transportable-udfs-trino/build.gradle
In order to make UDFs compiled by Transport can work with Trino v406, Transport needs to compile UDFs for Trino with Java 17.
Test
./gradlew clean build
cd transportable-udfs-example-udfs
./gradlew clean build
Also using javap -verbose classfile to confirm that the class files of UDFs for Trino are compiled with Java 17.
=> Upgrade Transport to compile Trino UDF with Java 17

transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/Defaults.java, transportable-udfs-test/transportable-udfs-test-trino/build.gradle, transportable-udfs-trino-plugin/build.gradle, transportable-udfs-trino-plugin/src/main/java/com/linkedin/transport/trino/TransportConnectorFactory.java, transportable-udfs-trino-plugin/src/main/java/com/linkedin/transport/trino/TransportConnectorMetadata.java, transportable-udfs-trino-plugin/src/test/java/com/linkedin/transport/trino/TransportPluginTest.java, transportable-udfs-trino/build.gradle
* In Trino
* `SHOW FUNCTIONS` retrieves function metadata from `ConnectorMetadata#listFunctions`
* `SHOW FUNCTIONS FROM ...` will check if the provided schema exists by `ConnectorMetadata#listSchemaNames`
* Schema name is expected to be in lower case.
* Make `TransportConnectorMetadata#getFunctions` compare in lower case because the schema function name is expected so
* Refactor `TransportPluginTest` usage of `LocalQueryRunner`
* Exclude dependencies with vulnerabilities under group id `com.nimbusds`. Transport does not depend on any class that uses them.
* Publish `.tar` distribution of `transportable-udfs-trino-plugin`
* Added unit test case for calling function name with camel case
* Added unit test case for `SHOW FUNCTIONS` usage
* Local end-to-end testing
* `./gradlew …
=> Fix corner case in TransportConnectorMetadata. Exclude com.nimbusds

build.gradle, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/Defaults.java, transportable-udfs-test/transportable-udfs-test-trino/build.gradle, transportable-udfs-trino-plugin/build.gradle, transportable-udfs-trino/build.gradle
* `slf4j-api` ver. 1.8+ is not backward compatible
* `nimbus-jose-jwt` ver. 9.31 is non-vulnerable
```
% ./gradlew transportable-udfs-trino:dependencies | grep nimbus-jose-jwt 
|    +--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31
|    |    \--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31 (*)
|    +--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31
|    |    \--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31 (*)
|    +--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31
|    |    \--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31 (*)
% ./gradlew transportable-udfs-trino-plugin:dependencies | grep nimbus-jose-jwt
+--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31
|    \--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31 (*)
+--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31
|    \--- com.nimbusds:nimbus-jose-jwt:9.14 -> 9.31 …
```
=> Remove slf4j-api 1.8+ and use nimbus-jose-jwt 9.31

transportable-udfs-api/src/main/java/com/linkedin/transport/api/types/StdStructType.java, transportable-udfs-avro/src/main/java/com/linkedin/transport/avro/types/AvroStructType.java, transportable-udfs-avro/src/test/java/com/linkedin/transport/avro/TestAvroWrapper.java, transportable-udfs-hive/src/main/java/com/linkedin/transport/hive/types/HiveStructType.java, transportable-udfs-hive/src/test/java/com/linkedin/transport/hive/typesystem/TestHiveTypes.java, transportable-udfs-spark_2.11/src/main/scala/com/linkedin/transport/spark/types/SparkTypes.scala, transportable-udfs-spark_2.11/src/test/scala/com/linkedin/transport/spark/TestSparkFactory.scala, transportable-udfs-trino/build.gradle, transportable-udfs-trino/src/main/java/com/linkedin/transport/trino/types/TrinoStructType.java, transportable-udfs-trino/src/test/java/com/linkedin/transport/trino/TestTrinoTypes.java
Adds a `fieldNames` method to StdStructType to return list of field names without having to operate on data.
It doesn't seem to be currently used as the names can also be accessible while working with actual data records. e.g. through implementations of `StdStruct#getField` with index or name. 
However, our usecase is to be able to do semantic validations of a JSON-like path representing a field in a dataset schema, using some sort of type representation, and this is one of the things needed for picking transport's type system as that type representation. cc @wmoustafa @khaitranq
=> Add support for getting field names

transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/packaging/ShadedJarPackaging.java, transportable-udfs-trino-plugin/build.gradle, version.properties
**Code Change**
- The code changes in `ShadedJarPackaging` to make UDF jars generated for multiple query engines (e.g. hive, spark, and trino) to be published as artifacts with Gradle 7
- The code changes in `transportable-udfs-trino-plugin/build.gradle` to exclude packaging of trino-spi.jar for the plugin
**Test**
./gradlew clean build
cd transportable-udfs-examples
./gradlew clean build
=> Publish UDF jars for multiple query engines as artifacts with Gradle 7

transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/packaging/DistributionPackaging.java, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/packaging/ThinJarPackaging.java
**Code Changes**
- As the jars generated for Trino is generated by the class of `ThinJarPackaging` and `DistributionPackaging`, making some code changes in both classes on how to generate the packaging task, so the jars generated from those packaging task can be published as artifacts with Gradle 7.
**Tests**
cd transport
./gradlew clean build
cd transportable-udfs-example
./gradlew clean build
test a UDF MP (e.g. standard-udfs-marketing) with a locally-built transport-plugin 
mint build
mint release
the content about the artifacts shown in buildspec.json include all jars
```
"artifacts": {
"marketing-std-udf": "ivy:/com.linkedin.standard-udfs-marketing/marketing-std-udf/1.0.7",
"marketing-std-udf:hive": "ivy:/com.linkedin.standard-udfs-marketing/marketing-std-udf/1.0.7", …
```
=> Fix packaging task for Trino with Gradle 7

transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/packaging/DistributionPackaging.java
**Code Change**
- With Gradle 7, the task to generate an build output needs to be added into `project.getArtifacts()` explicitly if the build output needs to be published as an artifact. Therefore in `DistributionPackaging.configurePackagingTasks`,  the task to generate `*-trino.tar` (`*-trino.zip) in as a distribution package are added into `project.getArtifacts()` explicitly
- Remove the task to generate `*-trino-dist-thin.jar` out of `project.getArtifacts()`
**Test**
cd transport
./gradlew clean build
// in a consumer UDF MP
./gradlew clean build
mint release
The resulted artifact list in the file of buildspec.json are as follows:
```
"artifacts": {
"marketing-std-udf": "ivy:/com.linkedin.standard-udfs-marketing/marketing-std-udf/1.0.7",
"marketing-std-udf:hive": …
```
=> Publish *-trino.tar(.zip) as an artifact for UDFs generated

transportable-udfs-examples/transportable-udfs-example-udfs/src/test/java/com/linkedin/transport/examples/TestFileLookupFunction.java, transportable-udfs-trino/src/main/java/com/linkedin/transport/trino/StdUdfWrapper.java
* Should fix the issues in #149 
* Trino engine does not invoke function when non-nullable arguments receive null value; this is determined by `FunctionMetadata#functionNullability`
* `FunctionMetadata#argumentNullability` expects `Boolean` object
* Revert changes in `TestFileLookUp`, since Trino actually throws `NullPointerException` in this case
=> Fix missing arguments nullability in FunctionMetadata

transportable-udfs-examples/transportable-udfs-example-udfs/build.gradle, transportable-udfs-test/transportable-udfs-test-generic/build.gradle, transportable-udfs-test/transportable-udfs-test-hive/build.gradle, transportable-udfs-test/transportable-udfs-test-trino/build.gradle
**Code Changes**
As consumer UDFs generated by Transport Plugin use `HiveTester` defined in the module of `transportable-udfs-hive-test` to execute the unit tests on UDF generated against Hive at run time and `HiveTester` depends on some classes from the libraries of `hadoop-common` and `hadoop-mapreduce-client-core`, two libraries are required at run time and they are added as `runtimeOnly` dependencies in the module of `transportable-udfs-hive-test`.
Also the test classes from `transportable-udfs-test-generic` and `transportable-udfs-test-trino` depends on hdfs library of Hadoop when the tests of UDF are executed at runtime. Therefore the runtimeOnly dependencies on two libraries are added into `transportable-udfs-test-generic` and `transportable-udfs-test-trino`. 
**Tests**
```
cd …
```
=> Add Hadoop libraries as runtimeOnly dependeny in transportable-udfs-test-hive/generic/trino

build.gradle, transportable-udfs-examples/build.gradle, transportable-udfs-plugin/build.gradle, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/TransportPlugin.java, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/packaging/DistributionPackaging.java, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/packaging/ShadedJarPackaging.java, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/packaging/ThinJarPackaging.java, transportable-udfs-plugin/src/main/java/com/linkedin/transport/plugin/tasks/ShadeTask.java
Upgrading shadow jar. This plugin source is outdated and preventing use within newer projects.
1. Project Builds Successfully
2. Unit Tests All Pass
=> Upgrade Shadow Jar Source

transportable-udfs-trino/src/main/java/com/linkedin/transport/trino/types/TrinoMapType.java
valueType() should return the valueType instead of the keytype of the map
=> Fix Bug in Trino Map ValueType
